name: publish
on: [workflow_dispatch]
jobs:
  publish-docker-image-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for master branch
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Docker image
        run: |
              docker build . -t ghcr.io/mrc4tt/steamrt3-pterodactyl:latest -f docker/Dockerfile
              docker push ghcr.io/mrc4tt/steamrt3-pterodactyl:latest
